### PR TITLE
init directory sync resources

### PR DESCRIPTION
**Pull request by TasDeniz**
init directory sync resources

### CODE REVIEW

**Review by RadovanTomik — COMMENTED** [review]
Would you like me to build the branch and test it?

**Comment by TasDeniz** [comment]
> Would you like me to build the branch and test it?

You can test ist with this image:
samply/share-client:gbn-pr-196

**Comment by RadovanTomik** [comment]
I cannot launch the connector. Whenever I access the GUI I get oops there is a bug somewhere. I'm attaching docker logs
[logs.txt](https://github.com/samply/share-client/files/9393485/logs.txt)

**Comment by RadovanTomik** [comment]
[logs.txt](https://github.com/samply/share-client/files/9394308/logs.txt)
Okay, now I can run the Job but the measure and the library resources are not initialized.

**Pull request merged**
